services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    working_dir: /var/www/ii-assistant
    volumes:
      - ../ii-assistant:/var/www/ii-assistant